# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FollowersGitHubiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FollowersGitHubiOS
  pod 'SwiftLint'
  pod 'Resolver'

  target 'FollowersGitHubiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
